version: "3.8"
services:
  packetbase:
    image: packetbase/api-gateway:latest
    build: .
    hostname: api-gateway
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - es-net
networks:
  es-net:
    name: es-net
    external: true
